version: 2
jobs:
  build1:
    docker: 
      - image: circleci/ruby
    steps:
      - checkout
      - run: echo "A first hello"
      - run: sleep 300
      - run: echo "Done"
  build2:
    docker: 
      - image: circleci/golang
    steps:
      - checkout
      - run: echo "A first hello"
      - run: sleep 300
      - run: echo "Done"
workflows:
  version: 2
  sequential_sleep
    jobs:
    - build1
    - build2
    - build1
    - build2
